[tool.poetry]
name = "nlp-spacy"
version = "0.1.0"
description = ""
authors = ["Abraham <cedenoabraham@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
spacy = "^3.8.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
